Repository canonical/documentation-builder, pull requests merged in 2018-08, with the labels that each got.

#132 Rename proxy in homepage examples
  docs/en/homepage-examples/snap-store-proxy-example.md
  docs/en/metadata.yaml
Labels: Review: Code +1

#131 Add canonical url to template
  tests/test_operations.py
  ubuntudesign/documentation_builder/builder.py
  ubuntudesign/documentation_builder/operations.py
  ubuntudesign/documentation_builder/resources/template.html
Labels: Review: Code +1, Review: QA +1

#133 Add base canonical passed to the templates
  tests/test_operations.py
  ubuntudesign/documentation_builder/builder.py
  ubuntudesign/documentation_builder/operations.py
  ubuntudesign/documentation_builder/resources/template.html
Labels: Review: Code needed, Review: QA needed
