Repository canonical/documentation-builder, pull requests merged in 2018-06, with the labels that each got.

#109 Fix the warning notifications
  CHANGES.txt
  docs/requirements.txt
  setup.py
  snap/snapcraft.yaml
  tests/fixtures/builder/output_basic/en/index.html
  tests/fixtures/builder/output_custom_template/en/index.html
  tests/fixtures/builder/output_media_path/en/index.html
  tests/fixtures/builder/output_media_url/en/index.html
  ubuntudesign/documentation_builder/extensions.py
  ubuntudesign/documentation_builder/resources/template.html
Labels: Review: Code +1, Review: Code needed, Review: QA +1, Review: QA needed

#110 Update base template with Vanilla 1.7.1 + docs styling
  tests/fixtures/builder/output_search/en/index.html
  tests/fixtures/builder/output_search/fr/index.html
  ubuntudesign/documentation_builder/resources/template.html
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#117 Allow custom footer text/links and remove leftover Vanilla markup
  ubuntudesign/documentation_builder/resources/template.html
Labels: Review: Code +1, Review: QA +1

#113 Bump to version 1.6.0
  CHANGES.txt
  docs/requirements.txt
  setup.py
  snap/snapcraft.yaml
Labels: Review: Code +1

#121 Add Snap Enterprise Proxy homepage example
  docs/en/homepage-examples/default.md
  docs/en/homepage-examples/enterprise-proxy-example.md
  docs/en/metadata.yaml
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#118 Add Juju homepage example
  docs/en/homepage-examples/juju-example.md
  docs/en/metadata.yaml
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#119 Add MAAS homepage example
  docs/en/homepage-examples/maas-example.md
  docs/en/metadata.yaml
Labels: Review: Code +1, Review: Design +1, Review: QA +1

#120 Add conjure up homepage example
  docs/en/homepage-examples/conjure-up-example.md
  docs/en/metadata.yaml
Labels: Review: Code +1, Review: Design +1, Review: QA +1
